--- #YAML:1.0
name:               Distribution-Cooker
version:            1.01
abstract:           Create a module directory from your own templates
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::IniFiles:  0
    Template:          0
    Test::More:        0.94
resources:
    Repository:  http://github.com/briandfoy/distribution-cooker/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
